# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CropSiteSuitabilityAnalysis
                                 A QGIS plugin
 Equal weighted overlay analysis for crop site suitability mapping.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-01
        copyright            : (C) 2025 by ICIMOD
        email                : nimes.bhandari@icimod.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CropSiteSuitabilityAnalysis class from file CropSiteSuitabilityAnalysis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .site_suitability_analysis import CropSiteSuitabilityAnalysis
    return CropSiteSuitabilityAnalysis(iface)
